#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("JustMovedGit.Resource", IsApplication=true)]

namespace JustMovedGit
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int budget = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int ehbo = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int favorieten = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int food = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int huishouden = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int logo = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int logoFont = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int logoIcon = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int planning = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int user = 2130837513;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f060017
			public const int LinearLayout = 2131099671;
			
			// aapt resource value: 0x7f060018
			public const int ListView = 2131099672;
			
			// aapt resource value: 0x7f060026
			public const int accountNaamEditText = 2131099686;
			
			// aapt resource value: 0x7f060006
			public const int budgetBtn = 2131099654;
			
			// aapt resource value: 0x7f06002a
			public const int createAccountBtn = 2131099690;
			
			// aapt resource value: 0x7f060014
			public const int favorietenBtn = 2131099668;
			
			// aapt resource value: 0x7f06001d
			public const int favorietenReceptBtn = 2131099677;
			
			// aapt resource value: 0x7f060004
			public const int gridLayout = 2131099652;
			
			// aapt resource value: 0x7f060008
			public const int huishoudenBtn = 2131099656;
			
			// aapt resource value: 0x7f060005
			public const int linearLayout1 = 2131099653;
			
			// aapt resource value: 0x7f060007
			public const int linearLayout2 = 2131099655;
			
			// aapt resource value: 0x7f06000a
			public const int linearLayout3 = 2131099658;
			
			// aapt resource value: 0x7f06000d
			public const int linearLayout4 = 2131099661;
			
			// aapt resource value: 0x7f060010
			public const int linearLayout5 = 2131099664;
			
			// aapt resource value: 0x7f060013
			public const int linearLayout6 = 2131099667;
			
			// aapt resource value: 0x7f060000
			public const int linearLayout7 = 2131099648;
			
			// aapt resource value: 0x7f060029
			public const int loginButton = 2131099689;
			
			// aapt resource value: 0x7f060011
			public const int plannenBtn = 2131099665;
			
			// aapt resource value: 0x7f06000b
			public const int receptBtn = 2131099659;
			
			// aapt resource value: 0x7f06001b
			public const int scrollView1 = 2131099675;
			
			// aapt resource value: 0x7f060016
			public const int searchBar = 2131099670;
			
			// aapt resource value: 0x7f060025
			public const int txtAccountNaam = 2131099685;
			
			// aapt resource value: 0x7f060002
			public const int txtBudget = 2131099650;
			
			// aapt resource value: 0x7f06000f
			public const int txtEhbo = 2131099663;
			
			// aapt resource value: 0x7f060015
			public const int txtFavorieten = 2131099669;
			
			// aapt resource value: 0x7f060009
			public const int txtHuishouden = 2131099657;
			
			// aapt resource value: 0x7f060012
			public const int txtPlanning = 2131099666;
			
			// aapt resource value: 0x7f060020
			public const int txtReceptBereidingstijd = 2131099680;
			
			// aapt resource value: 0x7f060023
			public const int txtReceptBereidingswijze = 2131099683;
			
			// aapt resource value: 0x7f06001e
			public const int txtReceptBeschrijving = 2131099678;
			
			// aapt resource value: 0x7f060021
			public const int txtReceptIngredienten = 2131099681;
			
			// aapt resource value: 0x7f060024
			public const int txtReceptKosten = 2131099684;
			
			// aapt resource value: 0x7f06001c
			public const int txtReceptTitel = 2131099676;
			
			// aapt resource value: 0x7f060022
			public const int txtReceptVoorbereiding = 2131099682;
			
			// aapt resource value: 0x7f06000c
			public const int txtRecepten = 2131099660;
			
			// aapt resource value: 0x7f06001f
			public const int txtSubTitel = 2131099679;
			
			// aapt resource value: 0x7f060019
			public const int txtTitel = 2131099673;
			
			// aapt resource value: 0x7f060027
			public const int txtWachtwoord = 2131099687;
			
			// aapt resource value: 0x7f060003
			public const int userButton = 2131099651;
			
			// aapt resource value: 0x7f060001
			public const int userMenu = 2131099649;
			
			// aapt resource value: 0x7f06000e
			public const int veiligheidBtn = 2131099662;
			
			// aapt resource value: 0x7f06001a
			public const int view1 = 2131099674;
			
			// aapt resource value: 0x7f060028
			public const int wachtwoordEditText = 2131099688;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Main = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int MenuView = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int OtherMenuListview = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int PlannenView = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int ReceptMenuListview = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int ReceptView = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int UserMenu = 2130903046;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040000
			public const int app_name = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f050000
			public const int Theme_Custom = 2131034112;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
